version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  ubuntu_test:
    machine: true
    environment:
      LANG: C.UTF-8
    steps:
      - run: id; pwd
      - checkout
      - run: sudo apt-get update -q && sudo apt-get install -q -y ca-certificates lxc lxc-templates
      - attach_workspace:
          at: /tmp/workspace
      - run: sudo lxc-create -n geotrek -t ubuntu -- -r bionic -b circleci
      - run: sudo lxc-start -n geotrek -d
      - run: sudo lxc-attach -n geotrek id
      - run: sudo lxc-attach -n geotrek pwd
      - run: sudo lxc-attach -n geotrek apt update
      - run: sudo lxc-attach -n geotrek apt install -y -q curl wget
      - run: sudo lxc-attach -n geotrek wget https://packages.geotrek.fr/ubuntu/pool/main/s/screamshotter/screamshotter_1.1.4_amd64.deb
      - run: sudo lxc-attach -n geotrek sudo apt install -q -y ./screamshotter_1.1.4_amd64.deb
      - run: sudo lxc-attach -n geotrek wget https://packages.geotrek.fr/ubuntu/pool/main/c/convertit/convertit_2.2.2_amd64.deb
      - run: sudo lxc-attach -n geotrek sudo apt install -q -y ./convertit_2.2.2_amd64.deb
      - run: sudo lxc-attach -n geotrek sudo debconf-set-selections .circleci/default.debconf
      - run: sudo lxc-attach -n geotrek sudo apt install -q -y /tmp/workspace/geotrek-admin_*_amd64.deb
      - run: sudo lxc-attach -n geotrek curl http://localhost
  ubuntu_package:
    docker:
      - image: ubuntu:bionic
    environment:
      LANG: C.UTF-8
    steps:
      - checkout
      - run: grep '^[0-9]\+\.[0-9]\+\.[0-9]\+$' VERSION || sed -i 's/~dev0/~dev<< pipeline.number >>/' debian/changelog
      - run: apt-get update -q && apt-get install -q -y dpkg-dev debhelper dh-virtualenv git python3 python3-venv python3-dev libgdal-dev libffi-dev libxml2-dev libxslt1-dev
      - run: dpkg-buildpackage -uc -us -b | cat
      - persist_to_workspace:
          root: /root
          paths: geotrek-admin_*_amd64.deb
workflows:
  version: 2
  all:
    jobs:
      - ubuntu_package
      - ubuntu_test:
          requires:
            - ubuntu_package
